name: Build FanboxEnumerator Chrome Extension

on:
  push:
    branches:
      - main # mainブランチへのpush時に実行
    paths:
      - 'FanboxEnumerator/_src/**' # FanboxEnumerator/_src ディレクトリ以下のファイル変更時のみ
      - '.github/workflows/build_fanbox_enumerator_extension.yml' # このワークフローファイル自体の変更時
  workflow_dispatch: # 手動実行も可能にする

permissions:
  contents: write # リポジトリへのコミット・プッシュのために必要

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version and date for naming from manifest
        id: version_info
        run: |
          MANIFEST_PATH="FanboxEnumerator/_src/manifest.json"
          if [ ! -f "$MANIFEST_PATH" ]; then
            echo "Error: $MANIFEST_PATH not found!"
            exit 1
          fi
          VERSION_STRING=$(jq -r .version "$MANIFEST_PATH") # 例: "2025.5.31.3"
          
          # YYYY.M.D.REV から各部分を抽出
          YEAR=$(echo "$VERSION_STRING" | cut -d. -f1)
          MONTH=$(echo "$VERSION_STRING" | cut -d. -f2)
          DAY=$(echo "$VERSION_STRING" | cut -d. -f3)
          REVISION=$(echo "$VERSION_STRING" | cut -d. -f4)

          # 月と日を2桁にフォーマット (先行ゼロ)
          FORMATTED_MONTH=$(printf "%02d" "$MONTH")
          FORMATTED_DAY=$(printf "%02d" "$DAY")
          
          DATE_FOR_FILENAME="${YEAR}${FORMATTED_MONTH}${FORMATTED_DAY}" # YYYYMMDD形式
          
          echo "Extracted manifest version: $VERSION_STRING"
          echo "Date for filename: $DATE_FOR_FILENAME"
          echo "Revision for filename: $REVISION"

          if [ -z "$YEAR" ] || [ -z "$MONTH" ] || [ -z "$DAY" ] || [ -z "$REVISION" ]; then
            echo "Error: Could not extract all parts from version string: $VERSION_STRING"
            exit 1
          fi

          ZIP_FILENAME="FanboxEnumerator_${DATE_FOR_FILENAME}_Rev${REVISION}.zip"
          
          echo "zip_filename=${ZIP_FILENAME}" >> $GITHUB_OUTPUT
          echo "Generated ZIP Filename: $ZIP_FILENAME"

      - name: Create ZIP archive
        working-directory: FanboxEnumerator/_src
        run: |
          zip -r ../../${{ steps.version_info.outputs.zip_filename }} . -x "*.DS_Store"
          echo "Created ZIP file at repository root: ${{ steps.version_info.outputs.zip_filename }}"

      - name: Create dist directory inside FanboxEnumerator
        working-directory: FanboxEnumerator
        run: mkdir -p dist
        
      - name: Move ZIP to FanboxEnumerator/dist directory
        run: mv ${{ steps.version_info.outputs.zip_filename }} FanboxEnumerator/dist/
        
      - name: List files in FanboxEnumerator/dist
        working-directory: FanboxEnumerator
        run: ls -l dist/

      - name: Commit and push ZIP file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add FanboxEnumerator/dist/${{ steps.version_info.outputs.zip_filename }}
          
          if git diff --staged --quiet; then
            echo "No changes to the extension package. Nothing to commit."
          else
            git commit -m "Automated: Build and package extension - ${{ steps.version_info.outputs.zip_filename }}"
            git pull --rebase origin main 
            git push
            echo "Extension package committed and pushed to FanboxEnumerator/dist/ directory."
          fi
